name: TamWorkflow

on:
    push:
        branches:
            - main

job:
    integration-delivery:
        runs-on: ubuntu-latest
        enviornment: Test
        container:
            image:none
        steps:
            name: Checkout code
            uses: actions/checkout@v3

            name: Install dependencies
            run: npm install 

            name: Build website
            run: npm run build