name: TeamWorkflow

on:
    push:
        branches:
            - master

jobs:
    integration-delivery:
        runs-on: ubuntu-latest
        environment: Test
        container:
            image: node
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install dependencies
                working-directory: BdeHandin
                run: npm install 

            -   name: Build website
                working-directory: BdeHandin
                run: npm run build
            
            -   name: FTP delivery
                uses: SamKirkland/FTP-Deploy-Action@4.3.3
                with:
                    server: ${{ vars.FTP_SERVER }}
                    username: ${{ secrets.FTP_USERNAME }}
                    password: ${{ secrets.FTP_PASSWORD }}
                    server-dir: test/todo/ # test.sustainabilityproject.one/todo/
                    local-dir: BdeHandin/dist/ # trailing slash is important
            
            -   name: Install TestCafe
                run: npm install -g testcafe

            -   name: Update APT
                run: apt-get update

            -   name: Install Chromium
                run: apt-get install -y chromium
            
            -   name: Run tests
                run: testcafe chromium:headless test/*
                

            